"""CapabilityRouter host protocol.

The router depends on public service-shaped methods, not Agent private field
names. Agent currently satisfies this protocol with thin wrappers around its
internal implementation; alternative hosts can implement the same stable port.
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class ToolHost(Protocol):
    """CapabilityRouter.dispatch 的宿主依赖面。"""

    # ── 身份 / 状态 ──
    session_id: str
    is_sub_agent: bool

    # ── allowlist 咽喉点 + 遥测（emit：typed AgentEvent 单出口，docs/16 #2）──
    def tool_blocked_by_allowlist(self, name: str) -> bool: ...
    def emit(self, event) -> bool: ...

    # ── 派发目标 ──
    async def spawn_background_shell(self, command: str, timeout_ms) -> str: ...
    def list_tasks(self, status=None, kind=None) -> str: ...
    def task_output(self, task_id: str, tail_bytes: int = 8000) -> str: ...
    async def stop_task(self, task_id: str) -> str: ...
    async def recall_memory_semantic(self, query: str, limit: int) -> str: ...
    async def spawn_memory_consolidate(self) -> str: ...
    async def execute_plan_mode_tool(self, name: str) -> str: ...
    async def execute_agent_tool(self, inp: dict) -> str: ...
    async def execute_skill_tool(self, inp: dict) -> str: ...
    async def run_real_tool(self, name: str, inp: dict) -> str: ...

    # ── hooks（pre/post-tool-use；fail-closed 门控在 _run_hook 内部）──
    def hooks_suppressed(self) -> bool: ...
    def has_active_hooks(self) -> bool: ...
    def matching_hooks(self, event: str, tool: str) -> list: ...
    async def run_hook(self, hook: dict, name: str, inp: dict, result): ...
