"""CapabilityRouter host protocol.

The router depends on public service-shaped methods, not Agent private field
names. Agent currently satisfies this protocol with thin wrappers around its
internal implementation; alternative hosts can implement the same stable port.
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class ToolHost(Protocol):
    """CapabilityRouter.dispatch 的宿主依赖面。"""

    # ── 身份 / 状态 ──
    session_id: str
    is_sub_agent: bool

    # ── allowlist 咽喉点 + 遥测（emit：typed AgentEvent 单出口，docs/16 #2）──
    def tool_blocked_by_allowlist(self, name: str) -> bool: ...
    def emit(self, event) -> bool: ...

    # ── docs/19：SandboxManager 规划上下文（runtime 注入，非模型）──
    def host_context(self, *, background: bool = ..., hook: bool = ...): ...
    def sandbox_policy(self, *, background: bool = ..., hook: bool = ...): ...

    # ── 派发目标 ──
    async def spawn_background_shell(self, command: str, timeout_ms) -> str: ...
    def list_tasks(self, status=None, kind=None) -> str: ...
    def task_output(self, task_id: str, tail_bytes: int = 8000) -> str: ...
    async def stop_task(self, task_id: str) -> str: ...
    def run_list(self, status: str | None = None) -> str: ...
    def run_status(self, child_session_id: str) -> str: ...
    def run_output(self, child_session_id: str, include_events: bool = False,
                   tail_events: int = 20) -> str: ...
    async def run_cancel(self, child_session_id: str) -> str: ...
    def run_send(self, child_session_id: str, prompt: str, *,
                 delivery: str = "steer", wake: bool = False) -> str: ...
    async def execute_memory_tool(self, inp: dict) -> str: ...
    async def spawn_memory_consolidate(self) -> str: ...
    async def execute_plan_mode_tool(self, name: str) -> str: ...
    async def execute_agent_tool(self, inp: dict) -> str: ...
    async def execute_skill_tool(self, inp: dict) -> str: ...
    async def run_real_tool(self, name: str, inp: dict) -> str: ...

    # ── docs/24 Phase 3：per-call ToolContext 铸造（host-routed 工具经 ctx 能力把手执行）──
    def mint_tool_context(self, name: str): ...

    # ── docs/24 Phase 4a：本 host 的 per-agent overlay registry（只读访问；schema 解析 +
    #    validate + host-routed tool.run 取自此表，绝不读全局 REGISTRY）──
    @property
    def registry(self): ...

    # ── hooks（pre/post-tool-use；fail-closed 门控在 _run_hook 内部）──
    def hooks_suppressed(self) -> bool: ...
    def has_active_hooks(self) -> bool: ...
    def matching_hooks(self, event: str, tool: str) -> list: ...
    async def run_hook(self, hook: dict, name: str, inp: dict, result): ...
